## **Numpy**

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as pl

In [4]:
list1 = [1, 2, 5, 6, 10]
print(list1)

[1, 2, 5, 6, 10]


The first method to make an array in numpy is to use the 'array' method

In [7]:
array = np.array(list1)
print(array)

[ 1  2  5  6 10]


Another common method to make an array of equally in-between distribtued values is linspace

In [17]:
prova = np.linspace(1, 100, 10, dtype=int)
prova

array([  1,  12,  23,  34,  45,  56,  67,  78,  89, 100])

Another common method could be the arange which depends on the step dimension

In [19]:
prova2 = np.arange(1, 10, 3)
prova2

array([1, 4, 7])

In [25]:
# To make the steps like in C, this is the way
v = np.arange(2, 2 + 31 * 5, 5)  # Start at 2, stop at 2 + 30 * 5, step of 5
print(v)

[  2   7  12  17  22  27  32  37  42  47  52  57  62  67  72  77  82  87
  92  97 102 107 112 117 122 127 132 137 142 147 152]
