In [6]:
from ttt_env import Game
from mcts import Node, MCTS
import numpy as np

In [7]:
tictactoe = Game()
player = 1

args = {
    'C': 1.41,
    'num_searches': 1000
}

mcts = MCTS(tictactoe, args)

state = tictactoe.get_initial_state()


while True:
    print(state)
    
    if player == 1:
        valid_moves = tictactoe.get_valid_moves(state)
        print("valid_moves", [i for i in range(tictactoe.action_size) if valid_moves[i] == 1])
        action = int(input(f"{player}:"))

        if valid_moves[action] == 0:
            print("action not valid")
            continue
            
    else:
        neutral_state = tictactoe.change_perspective(state, player)
        mcts_probs = mcts.search(neutral_state)
        action = np.argmax(mcts_probs)
        
    state = tictactoe.get_next_state(state, action, player)
    
    value, is_terminal = tictactoe.get_value_and_terminated(state, action)
    
    if is_terminal:
        print(state)
        if value == 1:
            print(player, "won")
        else:
            print("draw")
        break
        
    player = tictactoe.get_opponent(player)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
valid_moves [0, 1, 2, 3, 4, 5, 6, 7, 8]


1: 1


[[0. 1. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[ 0.  1.  0.]
 [ 0. -1.  0.]
 [ 0.  0.  0.]]
valid_moves [0, 2, 3, 5, 6, 7, 8]


1: 3


[[ 0.  1.  0.]
 [ 1. -1.  0.]
 [ 0.  0.  0.]]
[[-1.  1.  0.]
 [ 1. -1.  0.]
 [ 0.  0.  0.]]
valid_moves [2, 5, 6, 7, 8]


1: 2


[[-1.  1.  1.]
 [ 1. -1.  0.]
 [ 0.  0.  0.]]
[[-1.  1.  1.]
 [ 1. -1.  0.]
 [ 0.  0. -1.]]
-1 won
